### ISSUE TITLE
Transfer project to FINOS

### ISSUE THREAD

**Issue by maoo** [finos/secure-electron-adapter#1]
Transfer is scheduled on Wednesday 22 April,  1pm EST 

## Prior to transfer
- [x] Create project website homepage (1-pager) with same (basic) contents from README.md.
- [x] Review README.md and other FINOS blueprint contents, making sure contribution guidelines (how to send a PR, how to open an issue, how to get started, ...) are clear.
- [x] Add @finos-admin user as Admin to all GitHub repositories to contribute

## During the transfer
- [x] Transferring GitHub repositories (sea and quickstart) to github.com/finos
- [x] Test Git redirects
- [x] Test https://sea.finos.org

## After the transfer
- [x] Working with Marketing teams on project website and announcements
- [x] Create GitHub Action to test and build
- [ ] Release to FINOS NPM repo
- [ ] Add semantic release to automate release process

**Comment by mindthegab** [comment]
@maoo can this be closed?

**Comment by maoo** [comment]
Yes.

@mesner - feel free to ping me when you're ready to run the first release on FINOS npmjs. TY!
