### ISSUE TITLE
Add project logo to readme and sea.finos.org

### ISSUE THREAD

**Issue by mindthegab** [finos/secure-electron-adapter#5]
I [see](https://www.finos.org/blog/open-sourcing-our-secure-electron-adapter-a-game-changer-for-smart-desktop-technology) a logo for SEA exists.

Can we add it to the README and the sea.finos.org website?

**Comment by mesner** [comment]
Hi Gabriele.  I've added the logo to sea.finos.org and the readme.md files for secure-electron-adapter and sea-quick-start repositories. I committed to master in order to reference the images on sea.finos.org in the readme files, and to show the site.  Would you please review?

**Comment by mindthegab** [comment]
LGTM!
